### PR TITLE
Added Network options

### PR DESCRIPTION
**Pull request by jmassardo**
Greetings,

I wanted to be able to run several small demo robots on an existing wifi network so I added options to specify the gateway and subnet mask so my driver station could connect to the Arduino.

Thanks,
James

### CODE REVIEW

**Comment by ericbarch** [comment]
Looks good, thank you!

**Comment by jmassardo** [comment]
Good deal. I'm glad it's useful. Are there any other items you guys have down to add? I'm not a uber programmer by any means but I'd be happy to help if I can.

**Comment by ericbarch** [comment]
Just ported those changes to the other libraries. Nothing in the immediate queue but we're certainly open to feature requests. How has the library/Driverstation been working for you?

**Comment by jmassardo** [comment]
So far so good. Seems to be pretty straight forward for basic functions. I want to make a number of changes to the Driver Station app. The latency chart takes up a lot of room on the main screen and want to switch it to a dial. I'm planning on adding several other dials/gauges to the main screen so we can get some feedback from the robot. Speeds/position/sensors/etc. I'm also planning on adding a section to view a webcam on the robot. The arduino really isn't powerful enough to do vision or handle routing video so I'm leaning toward using a ethernet based cam  the same way we do with FRC bots.

We're building a couple demo robots for our FRC team. One will be a t-shirt cannon and the other will be a frisbee thrower bot. Since Arduinos are MUCH cheaper than the FRC control systems, I'm planning on using the RobotOpen libraries to teach basic programming and robot control. I'm hoping I can design a platform based on off the shelf components that's cheap enough that students can build their own at home.

**Comment by ajlapp** [comment]
This sounds great.  Driver Station upgrades is an area that we haven't been able to focus on.

Keep us posted on any upgrades you make.  Take a look on the driver station Git page.  I've listed some upgrade requests that are in line with what you've already mentioned.

Have you looked at Guino?  I experimented with it a bit for visualization and it had some cool features that would be slick to integrate.

**Comment by ajlapp** [comment]
Any action on these driver station updates?

**Comment by jmassardo** [comment]
I've tinkered with it a little. I'm trying to get the hang of the actual app is laid out and the conventions in the coding.

**Pull request merged**
